/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DateTimePicker {}
  interface DateTimePickerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'DateTimePicker': Components.DateTimePicker;
  }

  interface StencilIntrinsicElements {
    'date-time-picker': Components.DateTimePickerAttributes;
  }


  interface HTMLDateTimePickerElement extends Components.DateTimePicker, HTMLStencilElement {}
  var HTMLDateTimePickerElement: {
    prototype: HTMLDateTimePickerElement;
    new (): HTMLDateTimePickerElement;
  };

  interface HTMLElementTagNameMap {
    'date-time-picker': HTMLDateTimePickerElement
  }

  interface ElementTagNameMap {
    'date-time-picker': HTMLDateTimePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
